// This file is auto-generated by @hey-api/openapi-ts

export const $ChangeScriptRequest = {
    properties: {
        script_id: {
            type: 'string',
            title: 'Script Id'
        }
    },
    type: 'object',
    required: ['script_id'],
    title: 'ChangeScriptRequest'
} as const;

export const $GetScriptsResponse = {
    properties: {
        scripts: {
            items: {
                '$ref': '#/components/schemas/ScriptResponse'
            },
            type: 'array',
            title: 'Scripts'
        },
        current_script: {
            '$ref': '#/components/schemas/ScriptResponse'
        }
    },
    type: 'object',
    required: ['scripts', 'current_script'],
    title: 'GetScriptsResponse'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $PlayableScriptResponse = {
    properties: {
        script_id: {
            type: 'string',
            title: 'Script Id'
        },
        script_name: {
            type: 'string',
            title: 'Script Name'
        },
        min_player_number: {
            type: 'integer',
            title: 'Min Player Number'
        },
        max_player_number: {
            type: 'integer',
            title: 'Max Player Number'
        },
        keys: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Keys'
        }
    },
    type: 'object',
    required: ['script_id', 'script_name', 'min_player_number', 'max_player_number', 'keys'],
    title: 'PlayableScriptResponse'
} as const;

export const $ScriptResponse = {
    properties: {
        script_id: {
            type: 'string',
            title: 'Script Id'
        },
        script_name: {
            type: 'string',
            title: 'Script Name'
        },
        is_playable: {
            type: 'boolean',
            title: 'Is Playable'
        }
    },
    type: 'object',
    required: ['script_id', 'script_name', 'is_playable'],
    title: 'ScriptResponse'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;