// This file is auto-generated by @hey-api/openapi-ts

export const $ChangeScriptRequest = {
    properties: {
        script: {
            type: 'string',
            title: 'Script'
        }
    },
    type: 'object',
    required: ['script'],
    title: 'ChangeScriptRequest'
} as const;

export const $GetScriptsResponse = {
    properties: {
        scripts: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Scripts'
        },
        current_script: {
            type: 'string',
            title: 'Current Script'
        }
    },
    type: 'object',
    required: ['scripts', 'current_script'],
    title: 'GetScriptsResponse'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;