// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetScriptsError, GetScriptsResponse2, PostChangeScriptData, PostChangeScriptError, PostChangeScriptResponse, GetPlayableScriptData, GetPlayableScriptError, GetPlayableScriptResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Scripts
 */
export const getScripts = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetScriptsResponse2, GetScriptsError, ThrowOnError>({
    ...options,
    url: '/scripts'
}); };

/**
 * Change Script
 */
export const postChangeScript = <ThrowOnError extends boolean = false>(options: Options<PostChangeScriptData, ThrowOnError>) => { return (options?.client ?? client).post<PostChangeScriptResponse, PostChangeScriptError, ThrowOnError>({
    ...options,
    url: '/scripts/change'
}); };

/**
 * Playable Script
 */
export const getPlayableScript = <ThrowOnError extends boolean = false>(options: Options<GetPlayableScriptData, ThrowOnError>) => { return (options?.client ?? client).get<GetPlayableScriptResponse, GetPlayableScriptError, ThrowOnError>({
    ...options,
    url: '/scripts/playable/{script_id}'
}); };