// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetScriptsError, GetScriptsResponse, PostChangeScriptData, PostChangeScriptError, PostChangeScriptResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Scripts
 */
export const getScripts = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetScriptsResponse, GetScriptsError, ThrowOnError>({
    ...options,
    url: '/scripts'
}); };

/**
 * Change Script
 */
export const postChangeScript = <ThrowOnError extends boolean = false>(options: Options<PostChangeScriptData, ThrowOnError>) => { return (options?.client ?? client).post<PostChangeScriptResponse, PostChangeScriptError, ThrowOnError>({
    ...options,
    url: '/scripts/change'
}); };