// This file is auto-generated by @hey-api/openapi-ts

export type ChangeScriptRequest = {
    script: string;
};

export type GetScriptsResponse = {
    scripts: Array<(string)>;
    current_script: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetScriptsResponse2 = (GetScriptsResponse);

export type GetScriptsError = unknown;

export type PostChangeScriptData = {
    body: ChangeScriptRequest;
};

export type PostChangeScriptResponse = (unknown);

export type PostChangeScriptError = (HTTPValidationError);