// This file is auto-generated by @hey-api/openapi-ts

export type ChangeScriptRequest = {
    script_id: string;
};

export type GetScriptsResponse = {
    scripts: Array<ScriptResponse>;
    current_script: ScriptResponse;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type PlayableScriptResponse = {
    script_id: string;
    script_name: string;
    min_player_number: number;
    max_player_number: number;
    keys: Array<(string)>;
};

export type ScriptResponse = {
    script_id: string;
    script_name: string;
    is_playable: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetScriptsResponse2 = (GetScriptsResponse);

export type GetScriptsError = unknown;

export type PostChangeScriptData = {
    body: ChangeScriptRequest;
};

export type PostChangeScriptResponse = (unknown);

export type PostChangeScriptError = (HTTPValidationError);

export type GetPlayableScriptData = {
    path: {
        script_id: string;
    };
};

export type GetPlayableScriptResponse = (PlayableScriptResponse);

export type GetPlayableScriptError = (HTTPValidationError);